// Musical building blocks: drum grooves, hook rhythms and the moods that
// combine them. Pure data. Sound ids (pad, pluck, bass, kit, perc, texture)
// refer to entries in patches.js.
//
// Pattern strings are one bar of 16th notes. Digits are velocity (9 = full),
// "." is a rest. Bass letters: R root, r soft root, 5 fifth, O octave up.

/**
 * Groove shape:
 * {
 *   name, bpm: [lo, hi], swing: [lo, hi],
 *   kick, snare, hat, ohat: pattern strings,
 *   perc?: pattern string, played with the kit's perc sound,
 *   kit: default kit id (patches.js KITS),
 *   bass: [pattern strings], bassMax: longest bass note in steps,
 *   bassPatch?: bass id this groove insists on by default (e.g. '808'),
 *   rolls: true for 32nd-note hat rolls in drops,
 * }
 */
export const GROOVES = {
  four: {
    name: 'four on the floor',
    bpm: [122, 128],
    swing: [0, 0.03],
    kick: '9...9...9...9...',
    snare: '....9.......9...',
    hat: '.3.3.3.3.3.3.3.3',
    ohat: '..7...7...7...7.',
    kit: 'club',
    bass: ['..R...R...R...R.', '..R..rR...R..rR.', '..R...R.O.R...R.'],
    bassMax: 2,
    rolls: false,
  },
  halftime: {
    name: 'half-time',
    bpm: [140, 150],
    swing: [0, 0.03],
    kick: '9.........7.....',
    snare: '........9.......',
    hat: '7.4.6.4.7.4.6.4.',
    ohat: '................',
    kit: 'club',
    bass: ['R.........R.....', 'R.....r...R..5..'],
    bassMax: 10,
    bassPatch: '808',
    rolls: true,
  },
  breaks: {
    name: 'breakbeat',
    bpm: [126, 134],
    swing: [0, 0.05],
    kick: '9.....7...9.....',
    snare: '....9.......9..4',
    hat: '7.4.7.4.7.4.7.4.',
    ohat: '..............6.',
    kit: 'breaks',
    bass: ['R..R..R...R..5..', 'R.....R...R.r...'],
    bassMax: 3,
    rolls: false,
  },
  ballad: {
    name: 'slow ballad',
    bpm: [72, 84],
    swing: [0, 0.06],
    kick: '9.......7.5.....',
    snare: '....7.......7...',
    hat: '5.3.5.3.5.3.5.3.',
    ohat: '................',
    kit: 'soft',
    bass: ['R...............', 'R.......5.......'],
    bassMax: 16,
    rolls: false,
  },
  slowburn: {
    name: 'half-time ballad',
    bpm: [68, 78],
    swing: [0.04, 0.1],
    kick: '9......5..7.....',
    snare: '........8.......',
    hat: '4.3.4.3.4.3.4.3.',
    ohat: '..............4.',
    kit: 'softclap',
    bass: ['R.........5.....', 'R.......r.......'],
    bassMax: 10,
    rolls: true,
  },
  lofi: {
    name: 'lo-fi shuffle',
    bpm: [80, 90],
    swing: [0.18, 0.3],
    kick: '9......5..9.....',
    snare: '....7.......7...',
    hat: '5.3.5.3.5.3.5.3.',
    ohat: '................',
    kit: 'lofi',
    bass: ['R.....5...R.....', 'R.....R...5.....'],
    bassMax: 6,
    rolls: false,
  },
  chill: {
    name: 'chill bounce',
    bpm: [92, 102],
    swing: [0.08, 0.16],
    kick: '9...5.....9.....',
    snare: '....8.......8...',
    hat: '3.6.3.6.3.6.3.6.',
    ohat: '..............5.',
    kit: 'softclap',
    bass: ['R..R....5..R....', 'R.....5...R..r..'],
    bassMax: 4,
    rolls: false,
  },
  disco: {
    name: 'disco',
    bpm: [116, 124],
    swing: [0, 0.04],
    kick: '9...9...9...9...',
    snare: '....9.......9...',
    // closed hats leave a gap wherever the open hat lands
    hat: '53.353.353.353.3',
    ohat: '..8...8...8...8.',
    perc: '...5..6.....7.6.',
    kit: 'disco',
    bass: ['R.O.R.O.R.O.R.O.', 'R..OR.O.R..OR.O.', 'R.O.r.O.5.O.r.O.'],
    bassMax: 2,
    rolls: false,
  },
  bounce: {
    name: 'bouncy pop',
    bpm: [112, 120],
    swing: [0.04, 0.1],
    kick: '9.....8.9.....7.',
    snare: '....9.......9...',
    hat: '7.4.7.4.7.4.7.4.',
    ohat: '..............6.',
    perc: '..5..5....5..5..',
    kit: 'club',
    bass: ['R..O..R...R..O..', 'R..R..O.R..R..O.', 'R.....O.R..O..5.'],
    bassMax: 3,
    rolls: false,
  },
  trap: {
    name: 'trap',
    bpm: [136, 150],
    swing: [0, 0.03],
    kick: '9......7..9.....',
    snare: '........9.......',
    hat: '8.5.8.5.8.5.8.56',
    ohat: '................',
    perc: '......5......5..',
    kit: 'trap',
    bass: ['R......R..R.....', 'R.........R..5..', 'R.....r...R.....'],
    bassMax: 10,
    bassPatch: '808',
    rolls: true,
  },
  drill: {
    name: 'drill',
    bpm: [138, 146],
    swing: [0, 0.02],
    kick: '9.....7...7.....',
    snare: '........9.....7.',
    // dotted-8th hats drift against the beat
    hat: '7..5..7..5..7.5.',
    ohat: '................',
    perc: '...4.......4....',
    kit: 'trap',
    bass: ['R.....R...R.....', 'R.....R.......r.', 'R.........5.....'],
    bassMax: 8,
    bassPatch: '808',
    rolls: true,
  },
  boombap: {
    name: 'boom bap',
    bpm: [80, 88],
    swing: [0.18, 0.28],
    kick: '9.....7...9.....',
    snare: '....9.......9..3',
    hat: '6.4.6.4.6.4.6.4.',
    ohat: '..............4.',
    perc: '..3...3...3...3.',
    kit: 'boombap',
    bass: ['R.....R...5.....', 'R.........R..5..'],
    bassMax: 6,
    rolls: false,
  },
  lazy: {
    name: 'lazy swing',
    bpm: [72, 80],
    swing: [0.2, 0.3],
    kick: '9..5......8.....',
    snare: '....8.......8...',
    hat: '5.3.5.3.5.3.5.3.',
    ohat: '................',
    kit: 'boombap',
    bass: ['R.......5.......', 'R.....r.R.......'],
    bassMax: 8,
    rolls: false,
  },
  synthwave: {
    name: 'synthwave',
    bpm: [100, 112],
    swing: [0, 0.02],
    kick: '9.......9.......',
    snare: '....9.......9...',
    hat: '6.3.6.3.6.3.6.3.',
    ohat: '..............5.',
    kit: 'retro',
    bass: ['R.r.R.r.R.r.R.r.', 'R.r.R.r.R.r.O.r.', 'RrRrRrRrRrRrRrRr'],
    bassMax: 2,
    rolls: false,
  },
  outrun: {
    name: 'outrun',
    bpm: [108, 118],
    swing: [0, 0.02],
    kick: '9...9...9...9...',
    snare: '....9.......9...',
    hat: '43.343.343.343.3',
    ohat: '..5...5...5...5.',
    kit: 'retro',
    bass: ['RrRrRrRrRrRrRrRr', 'RrrRrrRrRrrRrrRr', 'R.r.R.r.R.r.R.r.'],
    bassMax: 2,
    rolls: false,
  },
  cinematic: {
    name: 'cinematic half-time',
    bpm: [84, 96],
    swing: [0, 0.03],
    kick: '9.........7.....',
    snare: '........9.......',
    hat: '5...4...5...4...',
    ohat: '................',
    perc: '......6......765',
    kit: 'cinematic',
    bass: ['R...............', 'R.......R.......', 'R.....R.R.......'],
    bassMax: 16,
    rolls: false,
  },
  wardrums: {
    name: 'war drums',
    bpm: [86, 94],
    swing: [0, 0.02],
    kick: '9.....7.....7...',
    snare: '........9.......',
    hat: '3.3.3.3.3.3.3.3.',
    ohat: '................',
    perc: '8..6..6.8.....76',
    kit: 'cinematic',
    bass: ['R.....R.....R...', 'R...........R...'],
    bassMax: 12,
    rolls: false,
  },
};

// Rhythms for the vocal hook, keyed by hook style. "x" = a chop. The first
// list opens a 2-bar phrase, the second answers it and leaves room.
export const HOOK_RHYTHMS = {
  sad: {
    call: ['x...x..x....x...', 'x.....x.x...x...', 'x..x....x.x.....', '..x.x...x...x...'],
    answer: ['x...x...x.......', 'x..x..x.........', 'x.....x.........'],
  },
  hype: {
    call: ['x..x..x.x.x..x..', 'x.x..x.xx..x.x..', 'x..x..x...x.x.x.', '..x..x..x.x..x..', 'x.xx..x.x..x..x.'],
    answer: ['x..x..x.x.......', 'x.x..x.x........', 'x..x..x...x.....'],
  },
  dreamy: {
    call: ['x...x.x...x.x...', '..x...x...x.x..x', 'x..x..x...x..x..', 'x.x...x.x...x...'],
    answer: ['x...x.x.........', 'x..x..x.........', '..x...x...x.....'],
  },
  // syncopated 16ths that keep landing just before the beat
  happy: {
    call: ['x..x..x...x.x...', 'x.x..x..x.x..x..', '..x.x..x..x.x.x.', 'x..x..x.x..x..x.', 'x.x.x...x..x.x..'],
    answer: ['x..x..x.x.......', '..x.x..x........', 'x.x..x..x.......'],
  },
  // half-time flow: few notes, triplet-ish gaps, room for the 808
  dark: {
    call: ['x..x..x.....x.x.', 'x.....x.x...x...', '..x..x..x.....x.', 'x..x......x..x..', 'x.x...x...x..x..'],
    answer: ['x..x..x.........', 'x.....x...x.....', '..x..x..x.......'],
  },
  // lazy, behind the beat, lots of space
  chill: {
    call: ['x...x.x.....x...', '..x...x.x...x...', 'x..x....x...x.x.', '..x.x...x.x.....', 'x.....x...x.x...'],
    answer: ['x...x...x.......', '..x...x.........', 'x..x....x.......'],
  },
  // straight 8ths, anthem-style
  retro: {
    call: ['x.x.x...x.x.x...', 'x...x.x.x...x.x.', 'x.x...x.x.x.x...', '..x.x.x...x.x.x.', 'x...x...x.x.x.x.'],
    answer: ['x.x.x...x.......', 'x...x.x.........', '..x.x.x.x.......'],
  },
  // long held notes, mostly on the beat
  epic: {
    call: ['x.....x.....x...', 'x.......x...x...', 'x...x...x...x...', 'x.....x...x.x...', '..x.....x...x...'],
    answer: ['x.......x.......', 'x.....x.........', 'x...x...........'],
  },
};

// Keys/pluck rhythms for the "stabs" and "pulse" styles.
export const KEYS_RHYTHMS = {
  stabs: ['x..x..x...x.x...', 'x..x..x.x..x.x..', '..x..x..x..x..x.'],
  pulse: ['..x...x...x...x.'],
};

export const KEYS_STYLES = {
  sustain: 'Held chords',
  arp8: 'Arp (8ths)',
  arp16: 'Arp (16ths)',
  stabs: 'Stabs',
  pulse: 'Offbeat pulse',
};

export const FILLS = ['.5.7', '5577', '3579', '..79', '7.77'];

/**
 * Mood shape:
 * {
 *   label, blurb (short pad description),
 *   colors: { dark, light }  accent colour per theme (light needs ~4.5:1 on #edece8),
 *   modes: [scale ids from theory.js SCALES; repeat one to weight it],
 *   progressions: { [mode]: [[scale degrees, 0-based, one chord per bar] x4] },
 *   seventhChance, ninthChance,
 *   grooves, pads, plucks, basses, kits, keysStyles: ids to pick from,
 *   bars: { intro, build, drop, outro }: allowed lengths (multiples of 4),
 *   introDrums: 'none' | 'hats' | 'light',
 *   pump: [lo, hi] sidechain depth, melodyLift: semitones above the voice,
 *   hook: { style: key of HOOK_RHYTHMS, maxLen, gate: [lo, hi], low, high },
 *   energy: drum velocity scale, padFilter: [closed Hz, open Hz],
 *   fx: { reverb, size, delay, feedback }: [lo, hi] each, 0-100,
 *   chop: { stutter, harmony, octave, vowel }: chances 0-1,
 *   texture: [texture ids, 'none' allowed] (background layer, patches.js TEXTURES),
 * }
 */
export const MOODS = {
  sad: {
    label: 'Sad',
    blurb: 'minor · 68–84 bpm · soft drums',
    colors: { dark: '#78aaff', light: '#2462cc' },
    modes: ['minor'],
    progressions: {
      minor: [
        [0, 5, 2, 6],
        [0, 3, 5, 4],
        [5, 6, 0, 0],
        [0, 6, 5, 6],
        [0, 3, 6, 2],
        [5, 3, 0, 4],
        [0, 5, 3, 4],
      ],
    },
    seventhChance: 0.5,
    ninthChance: 0.1,
    grooves: ['ballad', 'slowburn'],
    pads: ['warm', 'felt'],
    plucks: ['pluck', 'bell'],
    basses: ['sub'],
    kits: ['soft', 'softclap'],
    keysStyles: ['sustain', 'arp8'],
    bars: { intro: [4], build: [4], drop: [8], outro: [4] },
    introDrums: 'none',
    pump: [0.12, 0.25],
    melodyLift: 0,
    hook: { style: 'sad', maxLen: 6, gate: [0.8, 1], low: -2, high: 7 },
    energy: 0.75,
    padFilter: [550, 2400],
    fx: { reverb: [55, 75], size: [55, 85], delay: [30, 50], feedback: [35, 55] },
    chop: { stutter: 0.05, harmony: 0.3, octave: 0.2, vowel: 0.5 },
    texture: ['none', 'rain'],
  },
  hype: {
    label: 'Hype',
    blurb: 'minor · 122–150 bpm · pumping',
    colors: { dark: '#ff7b3a', light: '#cf460b' },
    modes: ['minor'],
    progressions: {
      minor: [
        [0, 5, 2, 6],
        [0, 5, 6, 0],
        [5, 6, 0, 0],
        [0, 3, 5, 6],
        [0, 6, 5, 6],
        [0, 5, 3, 6],
      ],
    },
    seventhChance: 0.25,
    ninthChance: 0,
    grooves: ['four', 'halftime', 'breaks'],
    pads: ['supersaw', 'warm'],
    plucks: ['stab'],
    basses: ['saw'],
    kits: ['club', 'breaks'],
    keysStyles: ['stabs', 'pulse', 'sustain'],
    bars: { intro: [4, 8], build: [8], drop: [16], outro: [4, 8] },
    introDrums: 'hats',
    pump: [0.55, 0.8],
    melodyLift: 5,
    hook: { style: 'hype', maxLen: 3, gate: [0.55, 0.85], low: -2, high: 7 },
    energy: 1,
    padFilter: [700, 9000],
    fx: { reverb: [30, 50], size: [35, 60], delay: [25, 45], feedback: [25, 45] },
    chop: { stutter: 0.35, harmony: 0.4, octave: 0.45, vowel: 0.4 },
    texture: ['none'],
  },
  dreamy: {
    label: 'Dreamy',
    blurb: 'major 7ths · 80–102 bpm · swing',
    colors: { dark: '#c9a2ff', light: '#7a42d4' },
    modes: ['major', 'major', 'lydian'],
    progressions: {
      major: [
        [3, 4, 2, 5],
        [0, 3, 5, 4],
        [0, 5, 3, 4],
        [3, 0, 4, 5],
        [5, 3, 0, 4],
        [0, 2, 3, 3],
      ],
      lydian: [
        [0, 1, 0, 1],
        [0, 1, 5, 4],
        [5, 1, 0, 0],
      ],
    },
    seventhChance: 0.85,
    ninthChance: 0.4,
    grooves: ['lofi', 'chill'],
    pads: ['glass', 'choir'],
    plucks: ['bell', 'pluck'],
    basses: ['round'],
    kits: ['lofi', 'softclap'],
    keysStyles: ['arp16', 'arp8', 'stabs'],
    bars: { intro: [4], build: [4], drop: [8, 12], outro: [4] },
    introDrums: 'light',
    pump: [0.2, 0.4],
    melodyLift: 3,
    hook: { style: 'dreamy', maxLen: 4, gate: [0.7, 0.95], low: -2, high: 8 },
    energy: 0.8,
    padFilter: [900, 4200],
    fx: { reverb: [60, 85], size: [60, 90], delay: [40, 60], feedback: [40, 60] },
    chop: { stutter: 0.1, harmony: 0.5, octave: 0.3, vowel: 0.6 },
    texture: ['none'],
  },
  happy: {
    label: 'Happy',
    blurb: 'major · 112–124 bpm · disco bounce',
    colors: { dark: '#c8e05a', light: '#5d7300' },
    modes: ['major', 'major', 'mixolydian'],
    progressions: {
      major: [
        [0, 4, 5, 3],
        [5, 3, 0, 4],
        [0, 5, 3, 4],
        [3, 4, 2, 5],
        [1, 4, 0, 5],
        [0, 3, 5, 4],
      ],
      mixolydian: [
        [0, 6, 3, 0],
        [0, 3, 6, 3],
        [0, 6, 3, 3],
        [0, 4, 6, 3],
        [3, 6, 0, 0],
      ],
    },
    seventhChance: 0.35,
    ninthChance: 0.1,
    grooves: ['disco', 'bounce'],
    pads: ['stringmachine', 'warm'],
    plucks: ['marimba', 'piano', 'stab'],
    basses: ['disco', 'round'],
    kits: ['disco', 'club'],
    keysStyles: ['stabs', 'pulse', 'arp8'],
    bars: { intro: [4], build: [4, 8], drop: [8, 16], outro: [4] },
    introDrums: 'hats',
    pump: [0.3, 0.5],
    melodyLift: 4,
    hook: { style: 'happy', maxLen: 3, gate: [0.6, 0.85], low: -2, high: 8 },
    energy: 0.95,
    padFilter: [800, 7000],
    fx: { reverb: [30, 50], size: [35, 60], delay: [25, 45], feedback: [25, 45] },
    chop: { stutter: 0.25, harmony: 0.5, octave: 0.4, vowel: 0.4 },
    texture: ['none'],
  },
  dark: {
    label: 'Dark',
    blurb: 'phrygian · 136–150 bpm · 808 trap',
    colors: { dark: '#ff4d5e', light: '#c4122a' },
    modes: ['phrygian', 'phrygian', 'minor'],
    progressions: {
      // bII (degree 1) is the menacing half-step up from the tonic
      phrygian: [
        [0, 1, 0, 1],
        [0, 1, 6, 0],
        [0, 5, 1, 0],
        [0, 3, 1, 0],
        [0, 6, 5, 1],
        [0, 2, 1, 0],
      ],
      minor: [
        [0, 0, 5, 4],
        [0, 5, 3, 4],
        [0, 3, 0, 5],
        [0, 5, 0, 4],
        [0, 3, 5, 4],
      ],
    },
    seventhChance: 0.1,
    ninthChance: 0,
    grooves: ['trap', 'drill'],
    pads: ['haunt', 'warm'],
    plucks: ['eerie', 'bell'],
    basses: ['808'],
    kits: ['trap', 'phonk'],
    keysStyles: ['arp8', 'sustain', 'pulse'],
    bars: { intro: [4, 8], build: [4], drop: [16], outro: [4] },
    introDrums: 'none',
    pump: [0.1, 0.3],
    melodyLift: 0,
    hook: { style: 'dark', maxLen: 4, gate: [0.6, 0.9], low: -3, high: 7 },
    energy: 1,
    padFilter: [400, 3200],
    fx: { reverb: [35, 55], size: [50, 80], delay: [30, 50], feedback: [30, 50] },
    chop: { stutter: 0.4, harmony: 0.2, octave: 0.35, vowel: 0.4 },
    texture: ['none', 'tape'],
  },
  chill: {
    label: 'Chill',
    blurb: 'dorian 9ths · 72–88 bpm · lo-fi swing',
    colors: { dark: '#6cc4b4', light: '#1c7266' },
    modes: ['dorian', 'dorian', 'minor'],
    progressions: {
      dorian: [
        [0, 3, 0, 3],
        [0, 3, 6, 2],
        [0, 3, 6, 4],
        [1, 4, 0, 3],
        [2, 1, 0, 6],
        [0, 4, 6, 3],
      ],
      minor: [
        [0, 3, 6, 2],
        [3, 6, 2, 5],
        [0, 4, 5, 3],
        [5, 4, 0, 0],
        [0, 5, 3, 4],
      ],
    },
    seventhChance: 0.9,
    ninthChance: 0.45,
    grooves: ['boombap', 'lazy', 'lofi'],
    pads: ['haze', 'felt'],
    plucks: ['rhodes', 'pluck'],
    basses: ['mellow', 'sub'],
    kits: ['boombap', 'lofi'],
    keysStyles: ['stabs', 'sustain', 'arp8'],
    bars: { intro: [4], build: [4], drop: [8, 12], outro: [4] },
    introDrums: 'light',
    pump: [0.1, 0.25],
    melodyLift: 2,
    hook: { style: 'chill', maxLen: 5, gate: [0.7, 0.95], low: -2, high: 7 },
    energy: 0.75,
    padFilter: [600, 2800],
    fx: { reverb: [45, 65], size: [45, 70], delay: [35, 55], feedback: [35, 55] },
    chop: { stutter: 0.08, harmony: 0.4, octave: 0.15, vowel: 0.6 },
    texture: ['vinyl', 'vinyl', 'rain'],
  },
  retro: {
    label: 'Retro',
    blurb: 'minor · 100–118 bpm · synthwave',
    colors: { dark: '#ff5fd2', light: '#c0189a' },
    modes: ['minor', 'minor', 'dorian'],
    progressions: {
      minor: [
        [0, 5, 2, 6],
        [0, 5, 6, 0],
        [5, 6, 0, 0],
        [0, 6, 5, 6],
        [0, 3, 5, 6],
        [0, 2, 3, 6],
      ],
      dorian: [
        [0, 6, 3, 3],
        [0, 2, 6, 3],
        [0, 3, 6, 0],
        [0, 4, 2, 3],
      ],
    },
    seventhChance: 0.25,
    ninthChance: 0.05,
    grooves: ['synthwave', 'outrun'],
    pads: ['brass', 'supersaw'],
    plucks: ['arp', 'stab'],
    basses: ['synthwave', 'saw'],
    kits: ['retro'],
    keysStyles: ['arp16', 'arp8', 'pulse'],
    bars: { intro: [4, 8], build: [4, 8], drop: [16], outro: [4] },
    introDrums: 'hats',
    pump: [0.25, 0.45],
    melodyLift: 3,
    hook: { style: 'retro', maxLen: 4, gate: [0.65, 0.9], low: -2, high: 7 },
    energy: 0.9,
    padFilter: [700, 6000],
    fx: { reverb: [50, 70], size: [55, 80], delay: [35, 55], feedback: [35, 55] },
    chop: { stutter: 0.15, harmony: 0.45, octave: 0.3, vowel: 0.5 },
    texture: ['none', 'tape'],
  },
  epic: {
    label: 'Epic',
    blurb: 'minor · 84–96 bpm · cinematic',
    colors: { dark: '#f0b429', light: '#8f6000' },
    modes: ['minor', 'minor', 'dorian'],
    progressions: {
      minor: [
        [0, 5, 2, 6],
        [0, 5, 6, 0],
        [5, 6, 0, 0],
        [0, 6, 5, 4],
        [0, 2, 6, 5],
        [5, 3, 0, 6],
      ],
      dorian: [
        [0, 2, 3, 0],
        [0, 6, 3, 0],
        [0, 6, 2, 3],
        [2, 6, 0, 0],
      ],
    },
    seventhChance: 0.1,
    ninthChance: 0,
    grooves: ['cinematic', 'wardrums'],
    pads: ['strings', 'choir'],
    plucks: ['brass', 'pluck'],
    basses: ['drone', 'sub'],
    kits: ['cinematic'],
    keysStyles: ['stabs', 'arp8', 'sustain'],
    bars: { intro: [4, 8], build: [4], drop: [8, 16], outro: [4] },
    introDrums: 'none',
    pump: [0.05, 0.2],
    melodyLift: -2,
    hook: { style: 'epic', maxLen: 8, gate: [0.85, 1], low: -3, high: 7 },
    energy: 0.9,
    padFilter: [500, 5000],
    fx: { reverb: [65, 90], size: [75, 100], delay: [25, 45], feedback: [30, 50] },
    chop: { stutter: 0.05, harmony: 0.55, octave: 0.3, vowel: 0.6 },
    texture: ['none'],
  },
};

export const MOOD_IDS = Object.keys(MOODS);

// Fallback progressions for when someone picks a scale the mood doesn't
// list. Every chord here is major or minor in that scale.
export const DEFAULT_PROGRESSIONS = {
  major: [
    [0, 4, 5, 3],
    [0, 5, 3, 4],
    [3, 4, 2, 5],
    [0, 3, 0, 4],
  ],
  minor: [
    [0, 5, 2, 6],
    [0, 3, 5, 4],
    [5, 6, 0, 0],
    [0, 6, 5, 6],
  ],
  dorian: [
    [0, 3, 0, 3],
    [0, 6, 3, 0],
    [0, 1, 6, 3],
    [0, 4, 6, 3],
  ],
  lydian: [
    [0, 1, 0, 1],
    [0, 1, 5, 4],
    [5, 1, 0, 0],
    [0, 4, 1, 0],
  ],
  phrygian: [
    [0, 1, 0, 1],
    [0, 1, 6, 0],
    [0, 5, 1, 0],
    [0, 6, 5, 1],
  ],
  mixolydian: [
    [0, 6, 3, 0],
    [0, 3, 6, 3],
    [0, 4, 6, 3],
    [6, 3, 0, 0],
  ],
};
